name = "T4AMPOContractions"
uuid = "953bfbbc-cb66-4acc-a854-9589b1f489b2"
version = "0.9.18"
authors = ["Simone Foder√† <simone.fodera@lmu.de>", "Ritter.Marc <Ritter.Marc@physik.uni-muenchen.de>, Hiroshi Shinaoka <h.shinaoka@gmail.com> and contributors"]

[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
T4ATensorCI = "14428447-6903-48c7-83df-f2cb08af9918"
T4ATensorTrain = "ec6ec972-96ae-4a21-b859-3911b77e305f"

[sources]
T4ATensorCI = {path = "../T4ATensorCI.jl"}
T4ATensorTrain = {path = "../T4ATensorTrain.jl"}

[compat]
Aqua = "0.8.14"
JET = "0.11.3"
MPI = "0.20.22"
MPIPreferences = "0.1.11"
Random = "1"
T4ATensorCI = "0.12"
T4ATensorTrain = "0.2"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Aqua", "Test", "Random", "Zygote", "Optim", "JET"]
